name: Build and Release

on:
  workflow_dispatch:
    inputs:
      tag:
        default: "latest"
        description: "Release tag"
        required: true
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VITE_SERVER_URL: https://eye.projectalita.ai/main/api/v1
      VITE_BASE_URI: alita_ui
      VITE_PUBLIC_PROJECT_ID: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 19

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build
        
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/
  release:
    needs: build
    runs-on: ubuntu-latest
    env:
      DEFAULT_TAG: "latest"

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist
          
      - name: Display structure of downloaded files
        run: ls -R
          
      - name: Zip artifacts
        run: zip -r dist.zip .

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: ./dist.zip
          makeLatest: true
          allowUpdates: true
          tag: ${{ github.event.inputs.tag || env.DEFAULT_TAG }}
