name: test deploy

on:
  workflow_dispatch:
    inputs:
      tag:
        default: "latest"
        description: "Release tag"
        required: true

env:
  DEFAULT_TAG: "latest"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger deploy
        run: |
          curl -X POST \
             -H "Authorization:Bearer ${{ secrets.UPDATE_TOKEN }}" \
             -H "Content-Type:application/json" \
             -d '{"release": "${{ github.event.inputs.tag || env.DEFAULT_TAG }}"}' \
             'https://eye.projectalita.ai/main/api/v1/alita_ui/ui_ci/administration'
          
